### PR TITLE
Event subscriptions

### PR DESCRIPTION
**Pull request by breyed**
Mechanism for subscribing to .NET events without COM registration.

### CODE REVIEW

**Comment by breyed** [comment]
This is an attempt to fill the gap in #11. We've tested the .NET code and plan to test the FoxPro side tomorrow. In the meantime, we may try to wrap the async call to `WaitForEvent`. In this usage, `AsyncCallbackEvents` is more heavy-weight than needed. `OnError` is never called.  `OnCompleted` would be better replaced by a function `OnEvent(lcEventName,loParameters)`.

**Comment by breyed** [comment]
I added a wrapper to call `OnEvent`. It could be made more elegant if it used dynamic code to call a FoxPro event named according to single .NET event subscribed to, with just its event parameter, rather than the current approach of subscribing to all events.

Additionally, there appears to be a problem with object lifetimes, which is difficult to debug, perhaps due to #13.

**Comment by breyed** [comment]
We modified the callback API to provide dispatch customized to the event and removed the need for the end user to call `WaitForEvent`. It's pretty cool - and works too! We haven't tested subscription lifetime yet. We plan to do so tomorrow.

`GetIndexedProperty` didn't work to get the raised event parameters from `lvResult.Params`. It always accessed the first array element. So we used an hack workaround instead.

**Comment by RickStrahl** [comment]
This all looks very nice - I'll take a look when I get a chance.

**Comment by RickStrahl** [comment]
I Edward,

I pulled this down and merged in the latest changes from master.

I'm trying to get my head around how this is supposed to work, but I'm not having any luck. Say I want to capture events from `FileSystemWatcher`.  I can't see how would set up the events to handle with the EventSubscriber and channel that all the way back to Foxpro.

Something like this?

```cs
var fw = new FileSystemWatcher();
var ev = new EventSubscriber(fw);

var result = ev.WaitForEvent();   // Keep this alive in a loop after event?
```

Then how do I get this back to FoxPro? Pass in an object that implements methods and try to call the method in the event with a T/C handler around it to guard against missing or invalid signatures? How does this thing stay alive then?

I guess I'm not sure how this is supposed work. It would help if you can set up an example perhaps that calls this through all the way to the client that's listening.

**Comment by RickStrahl** [comment]
Ok so I set this up with an example for the File System Watcher, but I don't see any events firing. I don't even see anything hitting the `QueueInteropEvent` handler in the .NET `EventSubscriber`. It looks like the subscriptions are working but the actual file update triggers are not happening.

I missed your sample above, so I ended up duplicating that code :-) Grrr...  Does your code above work for you? It doesn't for me - I see no events firing:

```foxpro
do wwDotNetBridge
LOCAL loBridge as wwDotNetBridge
loBridge = CreateObject("wwDotNetBridge","V4")

loFW = loBridge.CreateInstance("System.IO.FileSystemWatcher")
loFwHandler = CREATEOBJECT("FwEventHandler")
loSubscription = loBridge.SubscribeToEvents(loFw, loFwHandler)

lcFile = "c:\temp\test.txt"
DELETE FILE ( lcFile )  
STRTOFILE(lcFile,"DDD")
STRTOFILE(lcFile,"FFF")

WAIT WINDOW

RETURN


DEFINE CLASS FwEventHandler as Custom
FUNCTION OnChanged(sender,ev)
? "FILE CREATED: "
?  ev.Fullname
ENDFUNC

FUNCTION OnChanged(sender,ev)
? "FILE CHANGE: "
?  ev.Fullname
ENDFUNC

ENDDEFINE
```

I also don't even see any events firing into the .NET `QueueInteropEvent` handler even. I previously set up a .NET test that just sits and waits and the events weren't getting triggered there either.

The code looks like it's doing all the right things - I see the handlers getting hooked up and I assume the expression is doing the right thing (always a concern :-)). But I see no events getting forwarded into the handler.

Any ideas what I'm missing?

As to #13 I added exception handlers around the InvokeMethodAsync callbacks so if the handlers aren't there the exceptions at least won't crash VFP, but there is no feedback beyond the `LastException` getting set (which is of course not all that useful in Async scenarios).

**Comment by breyed** [comment]
Between jumping from the GitHub email to the web page for this issue, I missed the strikethrough on your first line. So when I copied your code from this issue web page and it didn't work, I wasn't surprised. To help debug, I added `EventTests.prg` as a member of the `Tests` project. It first tests with a simple `Loopback` class that simply raises an event. Then it tests with `FileSystemWatcher`. I did get the FileSystemWatcher test to work, but only after I added `SET SAFETY OFF`. It seems that the warning dialog interfered with how `InvokeMethodAsync`'s completion calls were getting injected into FoxPro.

We've tested events with a complex production application, and they're working perfectly, so I wasn't expecting any problems. The only remaining issue was lifetime support. There was a bug with the code in `EventSubscription` to unsubscribe when it went out of scope. The problem was that the async method held a reference to it, so even when the code that called `SubscribeToEvents` let the object it returned go out of scope, it still had a reference.

To fix the problem, I made subscription control explicit. `EventSubscription` now has an `Unsubscribe` method the user calls when done.

One other feature that might be nice would be for `SubscribeToEvents` to take an optional `prefix` parameter. When supplied, it would be used instead of `On`. That would allow subscribing to events from different classes without name conflicts.

Regarding the flow in GitHub, the recommended approach is to do all the editing in the PR issuer's repo. Once the update is stabilized, merge it into the upstream master branch. In our case, that would mean you deleting your breyed-events branch, us both making needed edits to my events branch, and when you think it's ready, you merging my events branch into your master branch, building and committing the release DLL, and then pushing your master to GitHub.

**Comment by RickStrahl** [comment]
Not sure why this branch is not showing as merged, but I'm closing this.

**Pull request merged**
